# Generated by Django 5.2.4 on 2025-10-23 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion_Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('estado', models.BooleanField()),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('carnet', models.IntegerField()),
                ('fecha_devolucion', models.DateField()),
                ('codigoActivo', models.JSONField(blank=True, default=list, help_text='Lista de códigos de activos asignados')),
            ],
        ),
        migrations.CreateModel(
            name='Line_Activo_Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('piso_ubicacion', models.CharField(choices=[('ALMACENES', 'ALMACENES'), ('PISO 5', 'PISO 5'), ('PISO 4', 'PISO 4'), ('PISO 3', 'PISO 3'), ('PISO 1', 'PISO 1'), ('SEGURIDAD', 'SEGURIDAD'), ('PATIO/GARAJE', 'PATIO/GARAJE'), ('TERRAZA', 'TERRAZA'), ('EXTRAVIADO/PERDIDO', 'EXTRAVIADO/PERDIDO'), ('EXTERNO', 'EXTERNO')])),
                ('oficina_ubicacion', models.CharField(choices=[('DIRECCION GENERAL EJECUTIVA', 'DIRECCION GENERAL EJECUTIVA'), ('DGE-SECRETARIA GENERAL', 'DGE-SECRETARIA GENERAL'), ('DGE-VENTANILLA UNICA', 'DGE-VENTANILLA UNICA'), ('DGE-COMUNICACION', 'DGE-COMUNICACION'), ('DGE-FINANCIAMIENTO', 'DGE-FINANCIAMIENTO'), ('ASESORIA LEGAL', 'ASESORIA LEGAL'), ('AUDITORIA INTERNA', 'AUDITORIA INTERNA'), ('GESTION INSTITUDIONAL Y DESARROLLO ORGANIZACIONAL', 'GESTION INSTITUDIONAL Y DESARROLLO ORGANIZACIONAL'), ('COORDINACION ADMINISTRATIVA FINANCIERA', 'COORDINACION ADMINISTRATIVA FINANCIERA'), ('ADMINISTRACION', 'ADMINISTRACION'), ('ADMINISTRACION-RECURSOS HUMANOS', 'ADMINISTRACION-RECURSOS HUMANOS'), ('ADMINISTRACION-ACTIVOS FIJOS', 'ADMINISTRACION-ACTIVOS FIJOS'), ('ADMINISTRACION-CONTRATACIONES', 'ADMINISTRACION-CONTRATACIONES'), ('ADMINISTRACION-ALMACENES', 'ADMINISTRACION-ALMACENES'), ('FINANZAS', 'FINANZAS'), ('COORDINACION DE PLANIFICACION Y EVALUACION DE PROYECTOS', 'COORDINACION DE PLANIFICACION Y EVALUACION DE PROYECTOS'), ('PLANIFICACION Y EVALUACION DE PROYECTOS', 'PLANIFICACION Y EVALUACION DE PROYECTOS'), ('CONTROL, SEGUIMIENTO Y MONITORIO DE PROYECTOS', 'CONTROL, SEGUIMIENTO Y MONITORIO DE PROYECTOS'), ('TRANSPARENCIA Y LUCHA CONTRA LA CORRUPCION', 'TRANSPARENCIA Y LUCHA CONTRA LA CORRUPCION'), ('TECNOLOGIAS DE INFORMACION Y COMUNICACION', 'TECNOLOGIAS DE INFORMACION Y COMUNICACION'), ('DATA CENTER', 'DATA CENTER'), ('ENTRADA', 'ENTRADA'), ('PASILLO', 'PASILLO'), ('ALMACEN', 'ALMACEN'), ('EXTERNO', 'EXTERNO')])),
                ('estado', models.CharField(choices=[('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Malo', 'Malo'), ('Baja', 'Baja'), ('Perdido', 'Perdido')])),
                ('observacion', models.TextField()),
            ],
            options={
                'verbose_name': 'Line_Activo_Responsable',
                'verbose_name_plural': 'Line_Activo_Responsable',
                'db_table': 'Line_Activo_Responsable',
            },
        ),
        migrations.CreateModel(
            name='Line_Asignacion_Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField()),
                ('observacion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Activo_responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piso_ubicacion', models.CharField(blank=True, choices=[('ALMACENES', 'ALMACENES'), ('PISO 5', 'PISO 5'), ('PISO 4', 'PISO 4'), ('PISO 3', 'PISO 3'), ('PISO 1', 'PISO 1'), ('SEGURIDAD', 'SEGURIDAD'), ('PATIO/GARAJE', 'PATIO/GARAJE'), ('TERRAZA', 'TERRAZA'), ('EXTRAVIADO/PERDIDO', 'EXTRAVIADO/PERDIDO'), ('EXTERNO', 'EXTERNO')], null=True)),
                ('oficina_ubicacion', models.CharField(blank=True, choices=[('DIRECCION GENERAL EJECUTIVA', 'DIRECCION GENERAL EJECUTIVA'), ('DGE-SECRETARIA GENERAL', 'DGE-SECRETARIA GENERAL'), ('DGE-VENTANILLA UNICA', 'DGE-VENTANILLA UNICA'), ('DGE-COMUNICACION', 'DGE-COMUNICACION'), ('DGE-FINANCIAMIENTO', 'DGE-FINANCIAMIENTO'), ('ASESORIA LEGAL', 'ASESORIA LEGAL'), ('AUDITORIA INTERNA', 'AUDITORIA INTERNA'), ('GESTION INSTITUDIONAL Y DESARROLLO ORGANIZACIONAL', 'GESTION INSTITUDIONAL Y DESARROLLO ORGANIZACIONAL'), ('COORDINACION ADMINISTRATIVA FINANCIERA', 'COORDINACION ADMINISTRATIVA FINANCIERA'), ('ADMINISTRACION', 'ADMINISTRACION'), ('ADMINISTRACION-RECURSOS HUMANOS', 'ADMINISTRACION-RECURSOS HUMANOS'), ('ADMINISTRACION-ACTIVOS FIJOS', 'ADMINISTRACION-ACTIVOS FIJOS'), ('ADMINISTRACION-CONTRATACIONES', 'ADMINISTRACION-CONTRATACIONES'), ('ADMINISTRACION-ALMACENES', 'ADMINISTRACION-ALMACENES'), ('FINANZAS', 'FINANZAS'), ('COORDINACION DE PLANIFICACION Y EVALUACION DE PROYECTOS', 'COORDINACION DE PLANIFICACION Y EVALUACION DE PROYECTOS'), ('PLANIFICACION Y EVALUACION DE PROYECTOS', 'PLANIFICACION Y EVALUACION DE PROYECTOS'), ('CONTROL, SEGUIMIENTO Y MONITORIO DE PROYECTOS', 'CONTROL, SEGUIMIENTO Y MONITORIO DE PROYECTOS'), ('TRANSPARENCIA Y LUCHA CONTRA LA CORRUPCION', 'TRANSPARENCIA Y LUCHA CONTRA LA CORRUPCION'), ('TECNOLOGIAS DE INFORMACION Y COMUNICACION', 'TECNOLOGIAS DE INFORMACION Y COMUNICACION'), ('DATA CENTER', 'DATA CENTER'), ('ENTRADA', 'ENTRADA'), ('PASILLO', 'PASILLO'), ('ALMACEN', 'ALMACEN'), ('EXTERNO', 'EXTERNO')], null=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activoResponsable', to='activos.activo', to_field='codigo')),
            ],
            options={
                'verbose_name': 'Activo_responsable',
                'verbose_name_plural': 'Activos_responsables',
                'db_table': 'Activo_responsable',
            },
        ),
    ]
