# Generated by Django 5.2.4 on 2025-11-13 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activos', '0002_initial'),
        ('designacion', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activo_responsable',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personaResponsable', to='users.personal', to_field='slug'),
        ),
        migrations.AddField(
            model_name='activo_responsable',
            name='asignacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignacionResponsable', to='designacion.asignacion'),
        ),
        migrations.AddField(
            model_name='devoluciones',
            name='asignacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devolucion', to='designacion.asignacion', to_field='slug'),
        ),
        migrations.AddField(
            model_name='line_activo_responsable',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='line_activo_responsable',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.personal', to_field='slug'),
        ),
        migrations.AddField(
            model_name='line_activo_responsable',
            name='slug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activos.activo', to_field='codigo'),
        ),
        migrations.AddField(
            model_name='line_asignacion',
            name='creador',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='line_asignacion',
            name='slug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designacion.asignacion'),
        ),
    ]
