# Generated by Django 5.2.4 on 2025-10-31 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designacion', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion_devolucion',
            name='cargo',
            field=models.CharField(default='c', max_length=255),
        ),
    ]
