# Generated by Django 5.2.4 on 2025-11-06 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0002_initial'),
        ('designacion', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line_activo_responsable',
            name='estado',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='line_activo_responsable',
            name='slug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activos.activo', to_field='codigo'),
        ),
    ]
