# Generated by Django 5.2.4 on 2025-11-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designacion', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devoluciones',
            name='tipoDevolucion',
            field=models.CharField(max_length=100, verbose_name=[('Semestral', 'Semestral'), ('Cuatrimestre', 'Cuatrimestre'), ('Trimestral', 'Trimestral'), ('Bimestral', 'Bimestral'), ('Mensual', 'Mensual')]),
        ),
    ]
