# Generated by Django 5.2.4 on 2025-11-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designacion', '0003_alter_line_activo_responsable_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devoluciones',
            name='fecha_devolucion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
