# Generated by Django 5.2.4 on 2025-11-05 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designacion', '0003_asignacion_devolucion_cargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('estado', models.BooleanField()),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('carnet', models.IntegerField()),
                ('cargo', models.CharField(default='c', max_length=255)),
                ('codigoActivo', models.JSONField(blank=True, default=list, help_text='Lista de códigos de activos asignados')),
            ],
        ),
        migrations.RemoveField(
            model_name='activo_responsable',
            name='asig_devol',
        ),
        migrations.AddField(
            model_name='activo_responsable',
            name='asignacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignacionResponsable', to='designacion.asignacion'),
        ),
        migrations.CreateModel(
            name='Devoluciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_devolucion', models.DateField()),
                ('tipoDevolucion', models.CharField(max_length=100, verbose_name=[('Parcial', 'Parcial'), ('Total', 'Total')])),
                ('codigoActivo', models.JSONField(blank=True, default=list, help_text='Lista de códigos de activos devueltos')),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devolucion', to='designacion.asignacion', to_field='slug')),
            ],
        ),
        migrations.CreateModel(
            name='Line_Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField()),
                ('observacion', models.TextField()),
                ('slug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designacion.asignacion')),
            ],
        ),
        migrations.DeleteModel(
            name='Line_Asignacion_Devolucion',
        ),
        migrations.DeleteModel(
            name='Asignacion_Devolucion',
        ),
    ]
