# Generated by Django 5.2.4 on 2025-11-05 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designacion', '0004_asignacion_remove_activo_responsable_asig_devol_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignacion',
            options={'verbose_name': 'Asignacion', 'verbose_name_plural': 'Asignaciones'},
        ),
        migrations.AlterModelOptions(
            name='devoluciones',
            options={'verbose_name': 'Devoluciones', 'verbose_name_plural': 'Devoluciones'},
        ),
        migrations.AlterModelTable(
            name='asignacion',
            table='Asignacion',
        ),
        migrations.AlterModelTable(
            name='devoluciones',
            table='Devoluciones',
        ),
    ]
