# Generated by Django 5.2.4 on 2025-11-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designacion', '0004_alter_devoluciones_fecha_devolucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='devoluciones',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
