# Generated by Django 5.2.4 on 2025-07-21 04:58

import django.db.models.deletion
import revision.upload
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_rename_edit_activos_user_g_activos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('motivo', models.CharField(choices=[('Revision Semestral', 'Revision Semestral')])),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('doc_Respaldo1', models.FileField(upload_to=revision.upload.doc_respaldo)),
                ('fechaHora_inicio', models.DateTimeField(blank=True, null=True)),
                ('fechaHora_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('encargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.personal')),
                ('revisores', models.ManyToManyField(blank=True, related_name='revisiones_apoyadas', to='users.personal')),
            ],
            options={
                'verbose_name': 'Revision',
                'verbose_name_plural': 'Revision',
                'db_table': 'Revisiones',
            },
        ),
        migrations.CreateModel(
            name='Revision_line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(max_length=255)),
                ('persona', models.CharField(max_length=255)),
                ('observacion', models.TextField()),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_datos', to='revision.revision')),
            ],
            options={
                'verbose_name': 'Revision_line',
                'verbose_name_plural': 'Revision_line',
                'db_table': 'Revision_line',
            },
        ),
    ]
