# Generated by Django 5.2.4 on 2025-11-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('motivo', models.CharField(choices=[('Revision General', 'Revision General'), ('Revision Personal', 'Revision Personal')])),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(null=True)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fechaHora_inicio', models.DateTimeField(blank=True, null=True)),
                ('fechaHora_finalizacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Revision',
                'verbose_name_plural': 'Revision',
                'db_table': 'Revisiones',
            },
        ),
        migrations.CreateModel(
            name='Revision_Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.TextField()),
            ],
            options={
                'verbose_name': 'Revision_Activo',
                'verbose_name_plural': 'Revision_Activo',
                'db_table': 'Revision_Activo',
            },
        ),
        migrations.CreateModel(
            name='Revision_line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(max_length=255)),
                ('creador', models.CharField(max_length=255)),
                ('observacion', models.TextField()),
            ],
            options={
                'verbose_name': 'Revision_line',
                'verbose_name_plural': 'Revision_line',
                'db_table': 'Revision_line',
            },
        ),
    ]
