# Generated by Django 5.2.4 on 2025-07-21 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revision', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revision_line',
            old_name='persona',
            new_name='creador',
        ),
    ]
