# Generated by Django 5.2.4 on 2025-11-13 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activos', '0002_initial'),
        ('revision', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='encargado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.personal', to_field='slug'),
        ),
        migrations.AddField(
            model_name='revision',
            name='revisores',
            field=models.ManyToManyField(blank=True, related_name='revisiones_apoyadas', to='users.personal'),
        ),
        migrations.AddField(
            model_name='revision_activo',
            name='activo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ActivoRevision', to='activos.activo', to_field='codigo'),
        ),
        migrations.AddField(
            model_name='revision_activo',
            name='encargado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encargadoRevision', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='revision_activo',
            name='revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_activos', to='revision.revision'),
        ),
        migrations.AddField(
            model_name='revision_line',
            name='revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_datos', to='revision.revision'),
        ),
    ]
