# Generated by Django 5.2.4 on 2025-11-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revision', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision_activo',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
