# Generated by Django 5.2.4 on 2025-07-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revision', '0002_rename_persona_revision_line_creador'),
        ('users', '0004_alter_personal_persona_alter_personal_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='revisores',
            field=models.ManyToManyField(blank=True, null=True, related_name='revisiones_apoyadas', to='users.personal'),
        ),
    ]
