# Generated by Django 5.2.4 on 2025-07-24 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revision', '0003_alter_revision_revisores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revision',
            name='doc_Respaldo1',
        ),
    ]
