# Generated by Django 5.2.4 on 2025-07-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revision', '0005_alter_revision_estado_alter_revision_revisores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='estado',
            field=models.BooleanField(null=True),
        ),
    ]
