# Generated by Django 5.2.4 on 2025-07-29 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0009_alter_activo_responsable_activo_and_more'),
        ('revision', '0006_alter_revision_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Revision_Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.TextField()),
                ('activo_res', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activo_responsable', to='activos.activo_responsable')),
                ('encargado', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='encargadoRevision', to=settings.AUTH_USER_MODEL)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_activos', to='revision.revision')),
            ],
            options={
                'verbose_name': 'Revision_Activo',
                'verbose_name_plural': 'Revision_Activo',
                'db_table': 'Revision_Activo',
            },
        ),
    ]
