# Generated by Django 5.2.4 on 2025-07-21 01:57

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=255)),
                ('contacto', models.IntegerField()),
                ('carnet', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'Persona',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='Usuario')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Registro')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_personal', models.BooleanField(default=False, verbose_name='Estado Personal')),
                ('is_revisor', models.BooleanField(default=False, verbose_name='Estado Revisor')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Estado Superuser')),
                ('vl_revisiones', models.BooleanField(default=False)),
                ('vl_TActivos', models.BooleanField(default=False)),
                ('edit_Activos', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'User',
            },
            managers=[
                ('objects', users.models.AccountManager()),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('persona', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.persona')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='revisor_perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personal',
                'verbose_name_plural': 'Personal',
                'db_table': 'Personal',
            },
        ),
        migrations.CreateModel(
            name='SuperUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='superuser_persona', to='users.persona')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='superuser_perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SuperUser',
                'verbose_name_plural': 'SuperUsers',
                'db_table': 'SuperUser',
            },
        ),
    ]
