# Generated by Django 5.2.4 on 2025-07-21 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='edit_Activos',
            new_name='g_Activos',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='vl_TActivos',
            new_name='g_personal',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='vl_revisiones',
            new_name='is_encargado',
        ),
        migrations.AddField(
            model_name='user',
            name='v_Activos',
            field=models.BooleanField(default=False),
        ),
    ]
