# Generated by Django 5.2.4 on 2025-07-21 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_edit_activos_user_g_activos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_perfil', to=settings.AUTH_USER_MODEL),
        ),
    ]
