# Generated by Django 5.2.4 on 2025-10-28 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linepersona',
            name='cargo_anterior',
        ),
        migrations.RemoveField(
            model_name='linepersona',
            name='contacto_anterior',
        ),
        migrations.AddField(
            model_name='linepersona',
            name='observacion',
            field=models.TextField(default='df'),
        ),
        migrations.AlterField(
            model_name='linepersona',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LinePersona', to='users.personal'),
        ),
    ]
