# Generated by Django 5.2.4 on 2025-07-21 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_personal_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.persona'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_perfil', to=settings.AUTH_USER_MODEL),
        ),
    ]
