# Generated by Django 5.2.4 on 2025-10-23 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Grupo Contable',
                'verbose_name_plural': 'Grupos Contables',
                'db_table': 'GruposContables',
            },
        ),
        migrations.CreateModel(
            name='Line_Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Malo', 'Malo'), ('Baja', 'Baja'), ('Perdido', 'Perdido')])),
                ('estadoActivo', models.CharField(blank=True, choices=[('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Malo', 'Malo'), ('Baja', 'Baja'), ('Perdido', 'Perdido')], null=True)),
                ('estadoDesignacion', models.BooleanField()),
                ('mantenimiento', models.BooleanField()),
                ('observacion', models.TextField()),
            ],
            options={
                'verbose_name': 'Line_Activo',
                'verbose_name_plural': 'Line_Activos',
                'db_table': 'Line_Activo',
            },
        ),
        migrations.CreateModel(
            name='MantenimientoActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField()),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField(blank=True, null=True)),
                ('descripcionInicio', models.TextField()),
                ('descripcionFin', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'MantenimientoActivo',
                'verbose_name_plural': 'MantenimientosActivos',
                'db_table': 'MantenimientoActivo',
            },
        ),
        migrations.CreateModel(
            name='AuxiliarContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('grupocontable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auxiliares', to='activos.grupocontable')),
            ],
            options={
                'verbose_name': 'Auxiliar Contable',
                'verbose_name_plural': 'Auxiliares Contables',
                'db_table': 'AuxiliarContable',
            },
        ),
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descActivo', models.TextField()),
                ('estadoActivo', models.CharField(blank=True, choices=[('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Malo', 'Malo'), ('Baja', 'Baja'), ('Perdido', 'Perdido')], null=True)),
                ('estadoDesignacion', models.BooleanField()),
                ('mantenimiento', models.BooleanField()),
                ('auxiliar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activos', to='activos.auxiliarcontable')),
                ('grupoContable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activos', to='activos.grupocontable')),
            ],
            options={
                'verbose_name': 'Activo',
                'verbose_name_plural': 'Activos',
                'db_table': 'Activo',
            },
        ),
    ]
