# Generated by Django 5.2.4 on 2025-11-06 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activos', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='line_activo',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mantenimientoactivo',
            name='activo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientosactivos', to='activos.activo'),
        ),
        migrations.AddField(
            model_name='mantenimientoactivo',
            name='asignadorFin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientoAsignadorFin', to='users.personal', to_field='slug'),
        ),
        migrations.AddField(
            model_name='mantenimientoactivo',
            name='asignadorInicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientoAsignadorInicio', to='users.personal', to_field='slug'),
        ),
        migrations.AlterUniqueTogether(
            name='auxiliarcontable',
            unique_together={('nombre', 'grupocontable')},
        ),
    ]
