# Generated by Django 5.2.4 on 2025-10-30 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line_activo',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='line_activo',
            name='slug',
        ),
        migrations.AddField(
            model_name='line_activo',
            name='activo',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='lineActivo', to='activos.activo'),
        ),
    ]
