# Generated by Django 5.2.4 on 2025-07-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0003_alter_activo_responsable_oficina_ubicacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activos_line',
            name='creador',
            field=models.CharField(default='q', max_length=100),
        ),
    ]
