# Generated by Django 5.2.4 on 2025-07-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0004_activos_line_creador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activo',
            name='estado',
        ),
        migrations.AddField(
            model_name='activo_responsable',
            name='estado',
            field=models.CharField(blank=True, choices=[('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Malo', 'Malo')], default='Bueno', null=True),
        ),
        migrations.AddField(
            model_name='activos_line',
            name='estado',
            field=models.CharField(blank=True, choices=[('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Malo', 'Malo')], default='Bueno', null=True),
        ),
    ]
