# Generated by Django 5.2.4 on 2025-07-21 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0007_alter_activos_line_responsable'),
        ('users', '0004_alter_personal_persona_alter_personal_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo_responsable',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.personal', to_field='slug'),
        ),
    ]
