# Generated by Django 5.2.4 on 2025-07-29 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0008_alter_activo_responsable_responsable'),
        ('users', '0004_alter_personal_persona_alter_personal_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo_responsable',
            name='activo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activoresponsablet', to='activos.activo', to_field='codigo'),
        ),
        migrations.AlterField(
            model_name='activo_responsable',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personaResponsable', to='users.personal', to_field='slug'),
        ),
    ]
